development:
  adapter: mysql2
  database: toolbox_search_development
  host: localhost 
  username: root
  password: 

production:
  adapter: mysql2
  database: toolbox_search
  host: localhost 
  username: root
  password: 1qaz2wsx

test:
  adapter: mysql2
  database: toolbox_search_test
  host: localhost 
  username: root
  password: 
